### ISSUE TITLE
Player set teleports

### ISSUE THREAD

**Issue by niekcandaele** [niekcandaele/CSMM-issues#38]
$settp 'name'
$removetp 'name'
$tp 'name'

**Comment by matt-bot1** [comment]
Admin ajustable number of teleports per player..

Private or public option for players

**Comment by matt-bot1** [comment]
Admin adjustable cooldown

**Comment by matt-bot1** [comment]
Also if possible have a teleport tab on csmm showing info like

Player name: teleport name: location: private/public:

**Comment by niekcandaele** [comment]
Added!
