### ISSUE TITLE
custom commands

### ISSUE THREAD

**Issue by matt-bot1** [niekcandaele/CSMM-issues#50]
let admins be able to add custom commands via csmm settings page 
custom commands as in a player types $animals  and csmm replys   se  {entity-id} 14

**Comment by niekcandaele** [comment]
Alright, to do this, I will need to expose some data to this custom command. Question is, which?

player - player executing the command
With parameters such as
- name
- level
- location (x,y,z)
- ...

Server
With parameters such as
- name
- ip
- animals
- zombies
- ...

Help me fill in what kinda data you want to use for these custom commands?
